# Generated by Django 5.0.2 on 2025-02-15 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notifications',
            name='heading',
        ),
        migrations.AddField(
            model_name='notifications',
            name='true',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='message',
            field=models.CharField(max_length=100),
        ),
    ]
