# Generated by Django 5.0.2 on 2025-02-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_remove_notifications_heading_notifications_true_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='message',
            new_name='notify',
        ),
    ]
