# Generated by Django 5.0.2 on 2025-02-14 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_usernft'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernft',
            name='ucoinid',
            field=models.IntegerField(default=1),
        ),
    ]
