# Generated by Django 5.0.2 on 2025-02-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_usernft_ucoinid'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tr_pin',
            field=models.IntegerField(blank=True, default=1, max_length=4),
            preserve_default=False,
        ),
    ]
