# Generated by Django 5.0.2 on 2025-02-17 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_profile_tr_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
